insert into member values (1, 1991, '2020-07-15', 'FEMALE', null)
insert into article values (1, '내용입니다1','2020-07-17','감정입니다1', true, 1)
insert into article values (2, '내용입니다2','2020-07-18','감정입니다2', false, 1)
insert into article values (3, '이 글은 300자짜리 글의 예시로써 작성된 글이다. 이것을 모두 작성하여 300자를 채우는 것은 어려운 일이나, 그것은 단순히 몸의 고초 혹여는 단순한 시간의 문제일 뿐 그것을 써내리는 것은 문제라기보다는 차라리 하나의 일로 생각하는 것이 편안한 것이다. 이렇게 작은 공간을 채우는 것조차 이렇게 힘겹다는 것은 때로 슬픈 일이 된다 그러나 그보다도 얼른 마저 이 분량을 채워야지 하는 생각을 하는 것이다  이렇게 써내리고도 겨우 200자 초반에 머무르고 있으니 언제야 300자를 채울까? 참으로 이런 것을 할 때에는 생각을 비우는 것이','2020-07-19','감정입니다3', true, 1)
insert into comment values (1, '댓글입니다1', '2020-07-20', false, '닉네임', 1, 1)
insert into comment values (2, '댓글입니다2', '2020-07-15', true, '닉네임', 1, 1)
insert into comment values (3, '댓글입니다3', '2020-07-15', false, '닉네임', 1, 1)
insert into comment values (4, '댓글입니다4', '2020-07-15', false, '닉네임', 3, 1)
insert into emotion values (1, 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/emojipedia/240/smiling-face-with-tear_1f972.png', '기뻐요')
insert into emotion values (2, 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/emojipedia/240/smiling-face-with-tear_1f972.png', '슬퍼요')
insert into emotion values (3, 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/emojipedia/240/smiling-face-with-tear_1f972.png', '화나요')
insert into emotion values (4, 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/emojipedia/240/smiling-face-with-tear_1f972.png', '4번이에요')
insert into emotion values (5, 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/emojipedia/240/smiling-face-with-tear_1f972.png', '5번이에요')
insert into emotion values (6, 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/emojipedia/240/smiling-face-with-tear_1f972.png', '6번이에')
insert into sub_emotion values (1, '행복해요', 1)
insert into sub_emotion values (2, '설레요', 1)
insert into sub_emotion values (3, '우울해요', 2)